[project]
name = 'Decentralized-Renewable-Energy-Certificate--REC--Trading-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.compliance-tracking]
path = 'contracts/compliance-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.rec-issuance]
path = 'contracts/rec-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.retirement]
path = 'contracts/retirement.clar'
clarity_version = 2
epoch = 2.5

[contracts.trading]
path = 'contracts/trading.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
